#!/bin/sh

[ -n "$IPKG_INSTROOT" ] || {
	/etc/uci-defaults/ackwrap || exit 1
	/etc/uci-defaults/50_luci-ackwrap || exit 1
	rm -f /tmp/luci-indexcache
	rm -rf /tmp/luci-modulecache
	/etc/init.d/ackwrap start || exit 1
}
exit 0
